#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80


# Update package list
apt-get update

# Install Nginx
apt-get install nginx -y

# Configure Nginx to listen on port 80
echo "server {
        listen 80;
        location / {
                echo 'Hello World!';
        }
}" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
