#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo cat > /etc/haproxy/haproxy.cfg << EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    user haproxy
    group haproxy
    maxconn 4096
    pidfile /var/run/haproxy.pid
    stats socket /var/run/haproxy.sock

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    option httpchk GET / HTTP/1.1\r\nHost:\ www
    server web-01 52.91.135.61:80 check
    server web-02 34.239.255.142:80 check
EOF

sudo service haproxy restart

