#!/usr/bin/env bash
# configures the container for nginx must be running as nginx user
# listening on all active IPs on port 8080

chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
#restart nginx
su nginx -s /bin/bash -c 'service nginx restart'
